### ISSUE TITLE
soil map

### ISSUE THREAD

**Issue by viatkin** [FAO-GSP/SOC-Mapping-Cookbook#10]
I'm checking continuity of the codes in the cookbook.
The cookbook has a code (optional) for rasterizing a soil map. Then the code for overlaying covariates (mandatory) refers to previously rasterized soil map. So, we need a soil map. The cookbook refers to a file "MK_soilmap_simple.shp". 
@midraed do you have this file?
? Do we keep soil map as a part of covariate stack in the (main) example or we leave it out?

**Comment by midraed** [comment]
shapefile with soilmap map is already in the repo. In the root folder.

Regarding the optional/mandatory problem: you are right. Maybe can leave the example in chapter 5. Because people want to know how to use information from shapefiles as covariates. So, is a needed example. In fact, I added this example following the request of many people.

However, in chapter 12 (code examples) we can remove the lines from the overlay script. So, because it shouldn't be mandatory.

**Comment by viatkin** [comment]
in chapter 12 optional-Rasterizing script, should we add something like this in the beginning?
(just to make the script work on its own)
library (raster)
soilmap <- shapefile("data/MK_soilmap_simple.shp")
DEM <- raster("covs/DEMENV5.tif")

**Comment by midraed** [comment]
yeah, add those lines
