### ISSUE TITLE
Chapter 12  - Image to be replaced

### ISSUE THREAD

**Issue by yigini** [FAO-GSP/SOC-Mapping-Cookbook#9]
I uploaded the image 3 times but it has not been replaced. It's still the old image!

Figure 1.1: Proposed graphical workflow for producing a SOC map from data preparation to final result publishing

**Comment by midraed** [comment]
is not automatic. I have to compile the book and produce the new pdf and
html if you want to see the new images.

Did you upload also the spline image? I don't see it!

Just in case, the spline image you sent before, is including the caption
below. PLease check if you removed the caption!

br

2018-04-06 9:06 GMT-03:00 yigini <notifications@github.com>:

**Comment by viatkin** [comment]
I uploaded spline image on Friday, it's here: https://github.com/FAO-GSP/SOC-Mapping-Cookbook/blob/master/images/spline.PNG. Yusuf also replaced the graphical workflow image, but we still see the old one on github for some reason... In the compiled version, it seems that my commits from Friday were not implemented...

**Comment by midraed** [comment]
My last update to compiled version was on Thursday. So, that's why you
don't see the changes from Friday. You can see it on the [commits list](
https://github.com/FAO-GSP/SOC-Mapping-Cookbook/commits/master). Usually,
when I update the html version I put "update html and pdf version" on the
commit message. The last update to graphical workflow image was 11 days
ago. When did @yigini update it? I'm attaching the one available on GitHub.
@yigini: can you check if its the same one?


![grworkflow](https://user-images.githubusercontent.com/2235494/38496173-e1fe3b78-3bd2-11e8-88f0-1cd02d449cd0.png)

2018-04-09 4:36 GMT-03:00 viatkin <notifications@github.com>:

**Comment by viatkin** [comment]
Ah, okay, I thought you updated the compiled version on Friday. No, grworkflow image on github is the old one.

**Comment by midraed** [comment]
ok. Can @yigini upload the new one?
BTW, I just updated the compiled version.

2018-04-09 9:35 GMT-03:00 viatkin <notifications@github.com>:

**Comment by yigini** [comment]
uploaded the new one grworkflow_latest.png
